/* Generated By:JavaCC: Do not edit this line. FscParserTreeConstants.java Version 5.0 */
package jp.dev7.enchant.doga.parser.fsc.autogen;

public interface FscParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFRAM = 1;
  public int JJTVOID = 2;
  public int JJTOBJDATA = 3;
  public int JJTFUNC = 4;
  public int JJTFUNCNAME = 5;
  public int JJTNUM = 6;


  public String[] jjtNodeName = {
    "Start",
    "Fram",
    "void",
    "ObjData",
    "Func",
    "FuncName",
    "Num",
  };
}
/* JavaCC - OriginalChecksum=c8cab6ee1453bb420e0189d6b08c6889 (do not edit this line) */
