/* Generated By:JavaCC: Do not edit this line. FscParserVisitor.java Version 5.0 */
package jp.dev7.enchant.doga.parser.fsc.autogen;

public interface FscParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTFram node, Object data);
  public Object visit(ASTObjData node, Object data);
  public Object visit(ASTFunc node, Object data);
  public Object visit(ASTFuncName node, Object data);
  public Object visit(ASTNum node, Object data);
}
/* JavaCC - OriginalChecksum=700fd10c9f11a93f4de7570d13a0e497 (do not edit this line) */
