/* Generated By:JJTree&JavaCC: Do not edit this line. FscParserConstants.java */
package jp.dev7.enchant.doga.parser.fsc.autogen;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FscParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int FRAM = 8;
  /** RegularExpression Id. */
  int OBJ = 9;
  /** RegularExpression Id. */
  int EYE = 10;
  /** RegularExpression Id. */
  int TARGET = 11;
  /** RegularExpression Id. */
  int LIGHT = 12;
  /** RegularExpression Id. */
  int NUM = 13;
  /** RegularExpression Id. */
  int NAME = 14;
  /** RegularExpression Id. */
  int NUMNAME = 15;
  /** RegularExpression Id. */
  int BLOCK_START = 16;
  /** RegularExpression Id. */
  int BLOCK_END = 17;
  /** RegularExpression Id. */
  int DATA_START = 18;
  /** RegularExpression Id. */
  int DATA_END = 19;
  /** RegularExpression Id. */
  int DQ = 20;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT_TEXT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"fram\"",
    "\"obj\"",
    "\"eye\"",
    "\"target\"",
    "\"light\"",
    "<NUM>",
    "<NAME>",
    "<NUMNAME>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
  };

}
