/* Generated By:JavaCC: Do not edit this line. PoseParserTreeConstants.java Version 5.0 */
package jp.dev7.enchant.doga.old.v4.parser.pose;

public interface PoseParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPOSE = 1;
  public int JJTUNITPOSE = 2;
  public int JJTNAME = 3;
  public int JJTNUM = 4;


  public String[] jjtNodeName = {
    "Start",
    "Pose",
    "UnitPose",
    "Name",
    "Num",
  };
}
/* JavaCC - OriginalChecksum=40f2e52f56762bdef00b10e9f42fabc8 (do not edit this line) */
