/* Generated By:JJTree: Do not edit this line. ASTShadeVertex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=jp.dev7.enchant.doga.parser.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.dev7.enchant.doga.parser.suf.autogen;

public class ASTShadeVertex extends SimpleNode {
    public ASTShadeVertex(int id) {
        super(id);
    }

    public ASTShadeVertex(SufParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(SufParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=d82686fa6c4b49ed94935c31d3578649 (do not edit this line) */
