/* Generated By:JJTree: Do not edit this line. ASTUvPolyVertex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=jp.dev7.enchant.doga.parser.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.dev7.enchant.doga.parser.suf.autogen;

public class ASTUvPolyVertex extends SimpleNode {
    public ASTUvPolyVertex(int id) {
        super(id);
    }

    public ASTUvPolyVertex(SufParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(SufParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=e0a50e41558561b4d5acf9ed94349f05 (do not edit this line) */
