/* Generated By:JJTree: Do not edit this line. ASTEmittion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=jp.dev7.enchant.doga.parser.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.dev7.enchant.doga.parser.atr.autogen;

public class ASTEmittion extends SimpleNode {
    public ASTEmittion(int id) {
        super(id);
    }

    public ASTEmittion(AtrParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(AtrParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=be3e0e514e51b6e70d387bc87507d0a9 (do not edit this line) */
