/* Generated By:JavaCC: Do not edit this line. AtrParserVisitor.java Version 5.0 */
package jp.dev7.enchant.doga.parser.atr.autogen;

public interface AtrParserVisitor {
    public Object visit(SimpleNode node, Object data);

    public Object visit(ASTStart node, Object data);

    public Object visit(ASTAtr node, Object data);

    public Object visit(ASTAtrName node, Object data);

    public Object visit(ASTFunc node, Object data);

    public Object visit(ASTNum node, Object data);

    public Object visit(ASTFilePath node, Object data);

    public Object visit(ASTEmittion node, Object data);
}
/* JavaCC - OriginalChecksum=cc85309efdf4b13dab6230b1ec5cfd85 (do not edit this line) */
