/* Generated By:JJTree&JavaCC: Do not edit this line. AtrParserConstants.java */
package jp.dev7.enchant.doga.parser.atr.autogen;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AtrParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int ATR = 8;
  /** RegularExpression Id. */
  int COLON = 9;
  /** RegularExpression Id. */
  int OPT = 10;
  /** RegularExpression Id. */
  int FUNCNAME = 11;
  /** RegularExpression Id. */
  int CASTSHADOW = 12;
  /** RegularExpression Id. */
  int RECEIVESHADOW = 13;
  /** RegularExpression Id. */
  int CELLLOOKEDGE = 14;
  /** RegularExpression Id. */
  int CELLLOOKSPECULAR = 15;
  /** RegularExpression Id. */
  int EDGECANCEL = 16;
  /** RegularExpression Id. */
  int EMITTION = 17;
  /** RegularExpression Id. */
  int EMPHASIS = 18;
  /** RegularExpression Id. */
  int DRAW = 19;
  /** RegularExpression Id. */
  int RATE = 20;
  /** RegularExpression Id. */
  int SHADER = 21;
  /** RegularExpression Id. */
  int NUM = 22;
  /** RegularExpression Id. */
  int NAME = 23;
  /** RegularExpression Id. */
  int BLOCK_START = 24;
  /** RegularExpression Id. */
  int BLOCK_END = 25;
  /** RegularExpression Id. */
  int DATA_START = 26;
  /** RegularExpression Id. */
  int DATA_END = 27;
  /** RegularExpression Id. */
  int DQ = 28;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT_TEXT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"atr\"",
    "\":\"",
    "\"opt\"",
    "<FUNCNAME>",
    "\"castshadow\"",
    "\"receiveshadow\"",
    "\"celllookedge\"",
    "\"celllookspecular\"",
    "\"edgecancel\"",
    "\"emittion\"",
    "\"emphasis\"",
    "\"draw\"",
    "\"rate\"",
    "\"shader\"",
    "<NUM>",
    "<NAME>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
  };

}
