/* Generated By:JavaCC: Do not edit this line. L3pParserVisitor.java Version 5.0 */
package jp.dev7.enchant.doga.parser.l3p.autogen;

public interface L3pParserVisitor {
    public Object visit(SimpleNode node, Object data);

    public Object visit(ASTStart node, Object data);

    public Object visit(ASTFram node, Object data);

    public Object visit(ASTObjData node, Object data);

    public Object visit(ASTFunc node, Object data);

    public Object visit(ASTFuncName node, Object data);

    public Object visit(ASTNum node, Object data);
}
/* JavaCC - OriginalChecksum=5bfe5f601aa58813811143fa0ef7a4f1 (do not edit this line) */
