/* Generated By:JavaCC: Do not edit this line. L3pParserTreeConstants.java Version 5.0 */
package jp.dev7.enchant.doga.parser.l3p.autogen;

public interface L3pParserTreeConstants {
    public int JJTSTART = 0;
    public int JJTFRAM = 1;
    public int JJTVOID = 2;
    public int JJTOBJDATA = 3;
    public int JJTFUNC = 4;
    public int JJTFUNCNAME = 5;
    public int JJTNUM = 6;

    public String[] jjtNodeName = { "Start", "Fram", "void", "ObjData", "Func",
            "FuncName", "Num", };
}
/* JavaCC - OriginalChecksum=318cd6845340ad9af8e9290505c1f411 (do not edit this line) */
