/* Generated By:JavaCC: Do not edit this line. L3cParserTreeConstants.java Version 5.0 */
package jp.dev7.enchant.doga.parser.l3c;

public interface L3cParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTUNIT = 2;
  public int JJTMOV = 3;
  public int JJTROTZ = 4;
  public int JJTROTY = 5;
  public int JJTROTX = 6;
  public int JJTOBJ = 7;
  public int JJTSCAL = 8;
  public int JJTUNITMOV = 9;
  public int JJTFUNC = 10;
  public int JJTNUM = 11;
  public int JJTTEXT = 12;
  public int JJTFILENAME = 13;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Unit",
    "Mov",
    "Rotz",
    "Roty",
    "Rotx",
    "Obj",
    "Scal",
    "UnitMov",
    "Func",
    "Num",
    "Text",
    "FileName",
  };
}
/* JavaCC - OriginalChecksum=0f04fa3ad506987994e9eeaf6946dbf7 (do not edit this line) */
