/* Generated By:JJTree: Do not edit this line. ASTFilePath.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=jp.dev7.enchant.doga.parser.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.dev7.enchant.doga.old.v4.parser.atr;

public
class ASTFilePath extends SimpleNode {
  public ASTFilePath(int id) {
    super(id);
  }

  public ASTFilePath(AtrParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AtrParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d0f3df3151ebee99ce2274b7dfa14303 (do not edit this line) */
