/* Generated By:JavaCC: Do not edit this line. AtrParserVisitor.java Version 5.0 */
package jp.dev7.enchant.doga.old.v4.parser.atr;

public interface AtrParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAtr node, Object data);
  public Object visit(ASTAtrName node, Object data);
  public Object visit(ASTFunc node, Object data);
  public Object visit(ASTNum node, Object data);
  public Object visit(ASTFilePath node, Object data);
  public Object visit(ASTEmittion node, Object data);
}
/* JavaCC - OriginalChecksum=ee31c9665e36ad7b57419420f9ac6722 (do not edit this line) */
