/* Generated By:JavaCC: Do not edit this line. SufParserTreeConstants.java Version 5.0 */
package jp.dev7.enchant.doga.old.v4.parser.suf;

public interface SufParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTOBJ = 1;
  public int JJTVOID = 2;
  public int JJTATTROBJ = 3;
  public int JJTATTRIBUTE = 4;
  public int JJTPRIMITIVE = 5;
  public int JJTPOLYGONVERTEX = 6;
  public int JJTSHADEVERTEX = 7;
  public int JJTUVPOLYVERTEX = 8;
  public int JJTUVSHADEVERTEX = 9;
  public int JJTX = 10;
  public int JJTY = 11;
  public int JJTZ = 12;
  public int JJTNORMALX = 13;
  public int JJTNORMALY = 14;
  public int JJTNORMALZ = 15;
  public int JJTU = 16;
  public int JJTV = 17;


  public String[] jjtNodeName = {
    "Start",
    "Obj",
    "void",
    "AttrObj",
    "Attribute",
    "Primitive",
    "PolygonVertex",
    "ShadeVertex",
    "UvPolyVertex",
    "UvShadeVertex",
    "X",
    "Y",
    "Z",
    "NormalX",
    "NormalY",
    "NormalZ",
    "U",
    "V",
  };
}
/* JavaCC - OriginalChecksum=4f0840a307daa20795244b42185e14b3 (do not edit this line) */
