/* Generated By:JavaCC: Do not edit this line. L3pParserTreeConstants.java Version 5.0 */
package jp.dev7.enchant.doga.old.v4.parser.l3p;

public interface L3pParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFRAM = 1;
  public int JJTVOID = 2;
  public int JJTOBJDATA = 3;
  public int JJTFUNC = 4;
  public int JJTFUNCNAME = 5;
  public int JJTNUM = 6;


  public String[] jjtNodeName = {
    "Start",
    "Fram",
    "void",
    "ObjData",
    "Func",
    "FuncName",
    "Num",
  };
}
/* JavaCC - OriginalChecksum=19e1c5d3b542220fa1dd87fbd73416e2 (do not edit this line) */
