/* Generated By:JavaCC: Do not edit this line. L3pParserVisitor.java Version 5.0 */
package jp.dev7.enchant.doga.old.v4.parser.l3p;

public interface L3pParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTFram node, Object data);
  public Object visit(ASTObjData node, Object data);
  public Object visit(ASTFunc node, Object data);
  public Object visit(ASTFuncName node, Object data);
  public Object visit(ASTNum node, Object data);
}
/* JavaCC - OriginalChecksum=ceaefb30b3dda87bb007b8245298c3e1 (do not edit this line) */
