/* Generated By:JJTree: Do not edit this line. ASTPose.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=jp.dev7.enchant.doga.parser.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.dev7.enchant.doga.parser.pose.autogen;

public class ASTPose extends SimpleNode {
    public ASTPose(int id) {
        super(id);
    }

    public ASTPose(PoseParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(PoseParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=6b6eee6385bded32b5e06a5a778e15b5 (do not edit this line) */
