/* Generated By:JavaCC: Do not edit this line. PoseParserTreeConstants.java Version 5.0 */
package jp.dev7.enchant.doga.parser.pose.autogen;

public interface PoseParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPOSE = 1;
  public int JJTUNITPOSE = 2;
  public int JJTNAME = 3;
  public int JJTNUM = 4;


  public String[] jjtNodeName = {
    "Start",
    "Pose",
    "UnitPose",
    "Name",
    "Num",
  };
}
/* JavaCC - OriginalChecksum=de17fbdd78079c2dd4f3b51b750a2c85 (do not edit this line) */
