/* Generated By:JJTree: Do not edit this line. ASTPolygonVertex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=jp.dev7.enchant.doga.parser.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.dev7.enchant.doga.parser.suf;

public
class ASTPolygonVertex extends SimpleNode {
  public ASTPolygonVertex(int id) {
    super(id);
  }

  public ASTPolygonVertex(SufParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SufParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=33f6f65e7fe05465d4afd6e6abe99696 (do not edit this line) */
