/* Generated By:JJTree&JavaCC: Do not edit this line. SufParserConstants.java */
package jp.dev7.enchant.doga.parser.suf;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SufParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int OBJ = 8;
  /** RegularExpression Id. */
  int SUF = 9;
  /** RegularExpression Id. */
  int ATR = 10;
  /** RegularExpression Id. */
  int PRIM = 11;
  /** RegularExpression Id. */
  int POLY = 12;
  /** RegularExpression Id. */
  int SHADE = 13;
  /** RegularExpression Id. */
  int UVPOLY = 14;
  /** RegularExpression Id. */
  int UVSHADE = 15;
  /** RegularExpression Id. */
  int NUM = 16;
  /** RegularExpression Id. */
  int NAME = 17;
  /** RegularExpression Id. */
  int BLOCK_START = 18;
  /** RegularExpression Id. */
  int BLOCK_END = 19;
  /** RegularExpression Id. */
  int DATA_START = 20;
  /** RegularExpression Id. */
  int DATA_END = 21;
  /** RegularExpression Id. */
  int DQ = 22;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT_TEXT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"obj\"",
    "\"suf\"",
    "\"atr\"",
    "\"prim\"",
    "\"poly\"",
    "\"shade\"",
    "\"uvpoly\"",
    "\"uvshade\"",
    "<NUM>",
    "<NAME>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
  };

}
