/* Generated By:JJTree: Do not edit this line. ASTUvShadeVertex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=jp.dev7.enchant.doga.parser.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.dev7.enchant.doga.parser.suf;

public
class ASTUvShadeVertex extends SimpleNode {
  public ASTUvShadeVertex(int id) {
    super(id);
  }

  public ASTUvShadeVertex(SufParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SufParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=88343a0610899da039ffe03a8cfa7048 (do not edit this line) */
