/* Generated By:JJTree: Do not edit this line. ASTUnitPose.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=jp.dev7.enchant.doga.parser.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.dev7.enchant.doga.parser.pose;

public
class ASTUnitPose extends SimpleNode {
  public ASTUnitPose(int id) {
    super(id);
  }

  public ASTUnitPose(PoseParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PoseParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a475c4f96ba87e622c64b910efa8029e (do not edit this line) */
