/* Generated By:JavaCC: Do not edit this line. PoseParserVisitor.java Version 5.0 */
package jp.dev7.enchant.doga.parser.pose;

public interface PoseParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTPose node, Object data);
  public Object visit(ASTUnitPose node, Object data);
  public Object visit(ASTName node, Object data);
  public Object visit(ASTNum node, Object data);
}
/* JavaCC - OriginalChecksum=8c12fc66de68858bd11e6faf70bbb2f3 (do not edit this line) */
