/* Generated By:JJTree: Do not edit this line. ASTUnitRot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=jp.dev7.enchant.doga.parser.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.dev7.enchant.doga.parser.posel2c.autogen;

public
class ASTUnitRot extends SimpleNode {
  public ASTUnitRot(int id) {
    super(id);
  }

  public ASTUnitRot(PoseL2cParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PoseL2cParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bd249169e0ea93cbbc5873a522b9029c (do not edit this line) */
