/* Generated By:JJTree: Do not edit this line. ASTUnitMov.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=jp.dev7.enchant.doga.parser.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.dev7.enchant.doga.parser.posel2c.autogen;

public
class ASTUnitMov extends SimpleNode {
  public ASTUnitMov(int id) {
    super(id);
  }

  public ASTUnitMov(PoseL2cParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PoseL2cParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4f2a01a0119b747f8d793e162ae028e4 (do not edit this line) */
