/* Generated By:JJTree: Do not edit this line. ASTUnitPose.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=jp.dev7.enchant.doga.parser.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.dev7.enchant.doga.parser.posel2c.autogen;

public
class ASTUnitPose extends SimpleNode {
  public ASTUnitPose(int id) {
    super(id);
  }

  public ASTUnitPose(PoseL2cParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PoseL2cParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=38013408e24486191da18fe676cc0390 (do not edit this line) */
