/* Generated By:JavaCC: Do not edit this line. PoseL2cParserTreeConstants.java Version 5.0 */
package jp.dev7.enchant.doga.parser.posel2c.autogen;

public interface PoseL2cParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPOSE = 1;
  public int JJTUNITMOV = 2;
  public int JJTUNITROT = 3;
  public int JJTNAME = 4;
  public int JJTNUM = 5;


  public String[] jjtNodeName = {
    "Start",
    "Pose",
    "UnitMov",
    "UnitRot",
    "Name",
    "Num",
  };
}
/* JavaCC - OriginalChecksum=7c3b38b0c570c89fd8ec6bc93872d6c8 (do not edit this line) */
