/* Generated By:JJTree&JavaCC: Do not edit this line. PoseL2cParserConstants.java */
package jp.dev7.enchant.doga.parser.posel2c.autogen;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PoseL2cParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int CM = 8;
  /** RegularExpression Id. */
  int DQ = 9;
  /** RegularExpression Id. */
  int DATA_START = 10;
  /** RegularExpression Id. */
  int DATA_END = 11;
  /** RegularExpression Id. */
  int NUM = 12;
  /** RegularExpression Id. */
  int NAME = 13;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT_TEXT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\":\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "<NUM>",
    "<NAME>",
  };

}
