/* Generated By:JavaCC: Do not edit this line. PoseL2cParserVisitor.java Version 5.0 */
package jp.dev7.enchant.doga.parser.posel2c.autogen;

public interface PoseL2cParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTPose node, Object data);
  public Object visit(ASTUnitMov node, Object data);
  public Object visit(ASTUnitRot node, Object data);
  public Object visit(ASTName node, Object data);
  public Object visit(ASTNum node, Object data);
}
/* JavaCC - OriginalChecksum=e8968626deb744f5f5e30ec16462d216 (do not edit this line) */
