/* Generated By:JavaCC: Do not edit this line. AtrParserTreeConstants.java Version 5.0 */
package jp.dev7.enchant.doga.parser.atr;

public interface AtrParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTATR = 1;
  public int JJTATRNAME = 2;
  public int JJTVOID = 3;
  public int JJTFUNC = 4;
  public int JJTNUM = 5;
  public int JJTFILEPATH = 6;
  public int JJTEMITTION = 7;


  public String[] jjtNodeName = {
    "Start",
    "Atr",
    "AtrName",
    "void",
    "Func",
    "Num",
    "FilePath",
    "Emittion",
  };
}
/* JavaCC - OriginalChecksum=b961ab3ee909656b26feee223f46de3d (do not edit this line) */
