/* Generated By:JavaCC: Do not edit this line. L3cParserVisitor.java Version 5.0 */
package jp.dev7.enchant.doga.old.v4.parser.l3c;

public interface L3cParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTUnit node, Object data);
  public Object visit(ASTMov node, Object data);
  public Object visit(ASTRotz node, Object data);
  public Object visit(ASTRoty node, Object data);
  public Object visit(ASTRotx node, Object data);
  public Object visit(ASTObj node, Object data);
  public Object visit(ASTScal node, Object data);
  public Object visit(ASTUnitMov node, Object data);
  public Object visit(ASTFunc node, Object data);
  public Object visit(ASTNum node, Object data);
  public Object visit(ASTText node, Object data);
  public Object visit(ASTFileName node, Object data);
}
/* JavaCC - OriginalChecksum=a6cda78013420d76f8647d5c8d6cc3e7 (do not edit this line) */
