/* Generated By:JJTree: Do not edit this line. ASTYens.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=jp.dev7.enchant.doga.parser.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.dev7.enchant.doga.parser.l2c.autogen;

public
class ASTYens extends SimpleNode {
  public ASTYens(int id) {
    super(id);
  }

  public ASTYens(L2cParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(L2cParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=92f17bcd3e418a86d3720a591afbbc8b (do not edit this line) */
